---

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  tags: ["cjdns", "cjdns-install", "cjdns-configure", "cjdns-service"]


- name: "Ensure cjdns is installed"
  become: true
  yum:
    name: "{{ item }}"
    state: "{{ cjdns_package_state }}"
  tags: ["cjdns", "cjdns-install"]
  with_items: "{{ cjdns_packages | list }}"


- name: "Configure cjdns"
  become: true
  template:
    src: "cjdroute.conf.j2"
    dest: "/etc/cjdroute.conf"
    backup: "yes"
    owner: "{{ cjdns_user }}"
    group: "{{ cjdns_group }}"
    mode: "0600"
  tags: ["cjdns", "cjdns-configure"]
  notify: ["restart cjdns"]


- name: "Manage cjdns service"
  become: true
  service:
    name: "{{ cjdns_service_name }}"
    state: "{{ cjdns_service_state }}"
    enabled: "{{ cjdns_service_enabled }}"
  tags: ["cjdns", "cjdns-service"]
